[package]
name = "rsa"
authors = []
type = "lib"
compiler_version = ">=0.22.0"

[dependencies]
large_integer = { tag = "main", git = "https://github.com/0xJepsen/noir-large-integer", directory = "crates/large-integer-64" }